source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'github-pages'
    gem "jekyll", ">= 3.7.4"
    gem 'jekyll-paginate'
    gem 'jekyll-scholar'
    gem 'jemoji'
    gem 'json'
    gem 'rake'
    gem 'front_matter_parser'
    gem "nokogiri", ">= 1.10.4"
    gem "rubyzip", ">= 1.2.2"
end
